CREATE TABLE "folders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "folders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 922337203685477 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"parent_id" bigint,
	"created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "folders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
--> statement-breakpoint
ALTER TABLE "notes" DROP CONSTRAINT "notes_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "notes" ALTER COLUMN "id" SET MAXVALUE 922337203685477;--> statement-breakpoint
ALTER TABLE "notes" ALTER COLUMN "title" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "notes" ADD COLUMN "folder_id" bigint;--> statement-breakpoint
ALTER TABLE "folders" ADD CONSTRAINT "folders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "folders" ADD CONSTRAINT "folders_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."folders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notes" ADD CONSTRAINT "notes_folder_id_fkey" FOREIGN KEY ("folder_id") REFERENCES "public"."folders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notes" ADD CONSTRAINT "notes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "Individuals can create their own folders." ON "folders" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));--> statement-breakpoint
CREATE POLICY "Individuals can delete their own folders." ON "folders" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));--> statement-breakpoint
CREATE POLICY "Individuals can update their own folders." ON "folders" AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));--> statement-breakpoint
CREATE POLICY "Individuals can view their own folders." ON "folders" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));--> statement-breakpoint
ALTER POLICY "Individuals can delete their own notes." ON "notes" TO public USING ((auth.uid() = user_id));--> statement-breakpoint
ALTER POLICY "Individuals can update their own notes." ON "notes" TO public USING ((auth.uid() = user_id));--> statement-breakpoint
ALTER POLICY "Individuals can view their own notes." ON "notes" TO public USING ((auth.uid() = user_id));